### ISSUE TITLE
running wdltool.jar

### ISSUE THREAD

**Issue by jayoung** [fhdsl/FH_WDL102_Workflows#10]
so now I'm learning about WDL using the Broad readthedocs. it's pretty clear for the most part.

this `womtools.jar inputs` tool looks cool, described in the "Generating the template JSON" section [here](https://wdl-docs.readthedocs.io/en/stable/WDL/specify_inputs/), albeit using an older name for the tool.

Is that something you ever do?  Is it worth adding that to the course?  or maybe this is all WDL102 content rather than 101.  

Took me a minute to figure out how I'd do it, so maybe that's worth including somewhere in the Hutch teaching materials
```
module load cromwell/84
java -jar $EBROOTCROMWELL/womtool.jar ....
```

**Comment by vortexing** [comment]
I think that's a great thing to include in WDL 102 and actually I wonder if I could get it to run inside the shiny app itself?!?!
